import { useState, useEffect } from 'react';
import ToolSelector from './ToolSelector';
import '../styles/AgentEditor.css';

type Platform = 'github-copilot' | 'claude' | 'cursor' | 'antigravity' | 'opencode';

const PLATFORM_LABELS: Record<Platform, string> = {
  'github-copilot': 'GitHub Copilot',
  claude: 'Claude',
  cursor: 'Cursor',
  antigravity: 'Antigravity',
  opencode: 'OpenCode',
};

const PLATFORM_FILENAMES: Record<Platform, string> = {
  'github-copilot': 'copilot-instructions.md',
  claude: 'CLAUDE.md',
  cursor: '{name}.mdc',
  antigravity: 'antigravity.config.json',
  opencode: 'instructions.md',
};

interface Agent {
  id: string;
  metadata: {
    name: string;
    version: string;
    description: string;
    author?: string;
    tags?: string[];
    compatibility: string[];
  };
  skills: any[];
  mcpConfig: {
    tools?: string[];
    target?: string;
  };
  instructions?: string;
}

interface AgentEditorProps {
  agentId: string | null;
  onAgentChange: (id: string | null) => void;
}

function AgentEditor({ agentId, onAgentChange }: AgentEditorProps) {
  const [agents, setAgents] = useState<Agent[]>([]);
  const [currentAgent, setCurrentAgent] = useState<Agent | null>(null);
  const [isEditing, setIsEditing] = useState(false);
  const [showToolSelector, setShowToolSelector] = useState(false);
  const [exportPlatform, setExportPlatform] = useState<Platform>('github-copilot');

  // PR modal state
  const [showPRModal, setShowPRModal] = useState(false);
  const [prOwnerRepo, setPrOwnerRepo] = useState('');
  const [prHead, setPrHead] = useState('');
  const [prBase, setPrBase] = useState('main');
  const [prTitle, setPrTitle] = useState('');
  const [prBody, setPrBody] = useState('');
  const [prCreating, setPrCreating] = useState(false);
  const [prResult, setPrResult] = useState<{ url: string; number: number } | null>(null);
  const [prError, setPrError] = useState<string | null>(null);

  useEffect(() => {
    loadAgents();
  }, []);

  useEffect(() => {
    if (agentId) {
      // Reset edit state when switching to a different agent
      setIsEditing(false);
      setShowToolSelector(false);
      loadAgent(agentId);
    } else {
      setIsEditing(false);
      setCurrentAgent(null);
    }
  }, [agentId]);

  const loadAgents = async () => {
    try {
      const loadedAgents = await window.api.agent.getAll();
      setAgents(loadedAgents);
    } catch (error) {
      console.error('Failed to load agents:', error);
    }
  };

  const loadAgent = async (id: string) => {
    try {
      const agent = await window.api.agent.getById(id);
      setCurrentAgent(agent);
    } catch (error) {
      console.error('Failed to load agent:', error);
    }
  };

  const createNewAgent = async () => {
    try {
      const newAgent = await window.api.agent.create({
        metadata: {
          name: 'New Agent',
          version: '1.0.0',
          description: '',
          compatibility: ['github-copilot', 'claude-code', 'opencode', 'cursor', 'antigravity'],
        },
        skills: [],
        mcpConfig: { tools: [], target: '' },
      });
      setAgents([...agents, newAgent]);
      onAgentChange(newAgent.id);
      setIsEditing(true);
    } catch (error) {
      console.error('Failed to create agent:', error);
    }
  };

  const saveAgent = async () => {
    if (!currentAgent) return;

    try {
      await window.api.agent.update(currentAgent.id, currentAgent);
      setIsEditing(false);
      loadAgents();
    } catch (error) {
      console.error('Failed to save agent:', error);
    }
  };

  const deleteAgent = async () => {
    if (!currentAgent) return;

    if (confirm(`Are you sure you want to delete "${currentAgent.metadata.name}"?`)) {
      try {
        await window.api.agent.delete(currentAgent.id);
        setCurrentAgent(null);
        onAgentChange(null);
        loadAgents();
      } catch (error) {
        console.error('Failed to delete agent:', error);
      }
    }
  };

  const exportToMd = async () => {
    if (!currentAgent) return;

    try {
      const content = await window.api.agent.exportToMd(currentAgent, exportPlatform);
      const isJson = exportPlatform === 'antigravity';
      const mimeType = isJson ? 'application/json' : 'text/markdown';
      const filename = PLATFORM_FILENAMES[exportPlatform].replace('{name}', currentAgent.metadata.name);
      const blob = new Blob([content], { type: mimeType });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = filename;
      a.click();
      URL.revokeObjectURL(url);
    } catch (error) {
      console.error('Failed to export agent:', error);
    }
  };

  const openPRModal = () => {
    if (!currentAgent) return;
    setPrTitle(`Add agent: ${currentAgent.metadata.name}`);
    setPrBody(`Adds the **${currentAgent.metadata.name}** agent configuration generated by Agent Orchestrator.\n\n${currentAgent.metadata.description || ''}`);
    setPrHead(`feat/add-agent-${currentAgent.metadata.name.replace(/\s+/g, '-').toLowerCase()}`);
    setPrResult(null);
    setPrError(null);
    setShowPRModal(true);
  };

  const handleCreatePR = async () => {
    if (!currentAgent) return;
    const [owner, repo] = prOwnerRepo.split('/');
    if (!owner || !repo || !prHead || !prTitle) {
      setPrError('Please fill in all required fields (owner/repo, head branch, title).');
      return;
    }
    setPrCreating(true);
    setPrError(null);
    try {
      // Export agent markdown and push to branch via GitHub API
      const content = await window.api.agent.exportToMd(currentAgent, 'github-copilot');
      await window.api.github.pushFiles(
        owner, repo, prBase, prHead,
        [{ path: '.github/copilot-instructions.md', content }],
        `chore: add ${currentAgent.metadata.name} agent config`,
      );
      const result = await window.api.github.createPR({ owner, repo, head: prHead, base: prBase, title: prTitle, body: prBody });
      setPrResult(result);
    } catch (e: any) {
      setPrError(e?.message || String(e));
    } finally {
      setPrCreating(false);
    }
  };

  const updateField = (path: string[], value: any) => {
    if (!currentAgent) return;

    // Deep clone to avoid mutating nested shared state
    const updated = structuredClone(currentAgent);
    let obj: any = updated;
    for (let i = 0; i < path.length - 1; i++) {
      obj = obj[path[i]];
    }
    obj[path[path.length - 1]] = value;
    setCurrentAgent(updated);
  };

  const addTool = () => {
    if (!currentAgent) return;
    const tools = currentAgent.mcpConfig.tools || [];
    updateField(['mcpConfig', 'tools'], [...tools, '']);
  };

  const removeTool = (index: number) => {
    if (!currentAgent) return;
    const tools = currentAgent.mcpConfig.tools || [];
    updateField(['mcpConfig', 'tools'], tools.filter((_, i) => i !== index));
  };

  const updateTool = (index: number, value: string) => {
    if (!currentAgent) return;
    const tools = [...(currentAgent.mcpConfig.tools || [])];
    tools[index] = value;
    updateField(['mcpConfig', 'tools'], tools);
  };

  return (
    <div className="agent-editor">
      <div className="agent-header">
        <h2>Agent Editor</h2>
        <div className="header-actions">
          <button className="btn btn-primary" onClick={createNewAgent}>
            + New Agent
          </button>
        </div>
      </div>

      <div className="editor-content">
        <div className="agent-list">
          <h3>Agents</h3>
          {agents.map((agent) => (
            <div
              key={agent.id}
              className={`agent-item ${agentId === agent.id ? 'active' : ''}`}
              onClick={() => onAgentChange(agent.id)}
            >
              <div className="agent-name">{agent.metadata.name}</div>
              <div className="agent-version">{agent.metadata.version}</div>
            </div>
          ))}
        </div>

        <div className="agent-details">
          {currentAgent ? (
            <>
              <div className="details-header">
                <h3>{isEditing ? 'Edit Agent' : currentAgent.metadata.name}</h3>
                <div className="details-actions">
                  {!isEditing ? (
                    <>
                      <button className="btn" onClick={() => setIsEditing(true)}>
                        Edit
                      </button>
                      <div className="export-group">
                        <select
                          className="platform-select"
                          value={exportPlatform}
                          onChange={(e) => setExportPlatform(e.target.value as Platform)}
                        >
                          {(Object.keys(PLATFORM_LABELS) as Platform[]).map(p => (
                            <option key={p} value={p}>{PLATFORM_LABELS[p]}</option>
                          ))}
                        </select>
                        <button className="btn" onClick={exportToMd}>
                          Export
                        </button>
                      </div>
                      <button className="btn btn-danger" onClick={deleteAgent}>
                        Delete
                      </button>
                      <button className="btn btn-github" onClick={openPRModal} title="Create GitHub Pull Request">
                        Create PR
                      </button>
                    </>
                  ) : (
                    <>
                      <button className="btn btn-primary" onClick={saveAgent}>
                        Save
                      </button>
                      <button className="btn" onClick={() => setIsEditing(false)}>
                        Cancel
                      </button>
                    </>
                  )}
                </div>
              </div>

              <div className="form-section">
                <h4>Metadata</h4>
                <div className="form-group">
                  <label>Name</label>
                  <input
                    type="text"
                    value={currentAgent.metadata.name}
                    onChange={(e) => updateField(['metadata', 'name'], e.target.value)}
                    disabled={!isEditing}
                  />
                </div>
                <div className="form-group">
                  <label>Version</label>
                  <input
                    type="text"
                    value={currentAgent.metadata.version}
                    onChange={(e) => updateField(['metadata', 'version'], e.target.value)}
                    disabled={!isEditing}
                  />
                </div>
                <div className="form-group">
                  <label>Description</label>
                  <textarea
                    value={currentAgent.metadata.description}
                    onChange={(e) => updateField(['metadata', 'description'], e.target.value)}
                    disabled={!isEditing}
                    rows={3}
                  />
                </div>
                <div className="form-group">
                  <label>Author</label>
                  <input
                    type="text"
                    value={currentAgent.metadata.author || ''}
                    onChange={(e) => updateField(['metadata', 'author'], e.target.value)}
                    disabled={!isEditing}
                  />
                </div>
              </div>

              <div className="form-section">
                <h4>MCP Configuration</h4>
                <div className="form-group">
                  <label>Target</label>
                  <select
                    value={currentAgent.mcpConfig.target || ''}
                    onChange={(e) => updateField(['mcpConfig', 'target'], e.target.value)}
                    disabled={!isEditing}
                  >
                    <option value="">Select target environment</option>
                    <option value="vscode">VS Code</option>
                    <option value="github">GitHub.com</option>
                    <option value="workspace">Workspace</option>
                    <option value="user">User</option>
                    <option value="global">Global</option>
                  </select>
                </div>
                <div className="form-group">
                  <label>Tools</label>
                  {isEditing && (
                    <button 
                      className="btn btn-sm" 
                      onClick={() => setShowToolSelector(!showToolSelector)}
                      style={{ marginBottom: '0.5rem' }}
                    >
                      {showToolSelector ? '✕ Hide' : '🔧 Select from Registry'}
                    </button>
                  )}
                  
                  {showToolSelector && isEditing && (
                    <ToolSelector
                      selectedTools={currentAgent.mcpConfig.tools || []}
                      onToolsChange={(tools) => updateField(['mcpConfig', 'tools'], tools)}
                    />
                  )}
                  
                  {currentAgent.mcpConfig.tools?.map((tool, index) => (
                    <div key={index} className="tool-item">
                      <input
                        type="text"
                        value={tool}
                        onChange={(e) => updateTool(index, e.target.value)}
                        disabled={!isEditing}
                        placeholder="Tool name"
                      />
                      {isEditing && (
                        <button
                          className="btn btn-sm btn-danger"
                          onClick={() => removeTool(index)}
                        >
                          Remove
                        </button>
                      )}
                    </div>
                  ))}
                  {isEditing && (
                    <button className="btn btn-sm" onClick={addTool}>
                      + Add Tool Manually
                    </button>
                  )}
                </div>
              </div>

              <div className="form-section">
                <h4>Instructions</h4>
                <div className="form-group">
                  <textarea
                    value={currentAgent.instructions || ''}
                    onChange={(e) => updateField(['instructions'], e.target.value)}
                    disabled={!isEditing}
                    rows={10}
                    placeholder="Enter custom instructions for the agent..."
                  />
                </div>
              </div>
            </>
          ) : (
            <div className="empty-state">
              <p>Select an agent to view details or create a new one</p>
            </div>
          )}
        </div>
      </div>
      {/* PR Modal */}
      {showPRModal && (
        <div className="modal-overlay" onClick={() => !prCreating && setShowPRModal(false)}>
          <div className="modal-content pr-modal" onClick={e => e.stopPropagation()}>
            <div className="modal-header">
              <h3>Create GitHub Pull Request</h3>
              <button className="modal-close" onClick={() => setShowPRModal(false)} disabled={prCreating}>✕</button>
            </div>

            {prResult ? (
              <div className="pr-success">
                <p>✅ Pull Request <strong>#{prResult.number}</strong> created successfully!</p>
                <a href={prResult.url} target="_blank" rel="noreferrer" className="btn btn-primary">
                  View PR on GitHub
                </a>
                <button className="btn" onClick={() => setShowPRModal(false)} style={{ marginLeft: '8px' }}>Close</button>
              </div>
            ) : (
              <div className="pr-form">
                <div className="form-group">
                  <label>Repository <span className="required">*</span></label>
                  <input
                    type="text"
                    placeholder="owner/repo"
                    value={prOwnerRepo}
                    onChange={e => setPrOwnerRepo(e.target.value)}
                    disabled={prCreating}
                  />
                </div>
                <div className="form-row">
                  <div className="form-group">
                    <label>Base branch <span className="required">*</span></label>
                    <input
                      type="text"
                      value={prBase}
                      onChange={e => setPrBase(e.target.value)}
                      disabled={prCreating}
                    />
                  </div>
                  <div className="form-group">
                    <label>Head branch <span className="required">*</span></label>
                    <input
                      type="text"
                      value={prHead}
                      onChange={e => setPrHead(e.target.value)}
                      disabled={prCreating}
                    />
                  </div>
                </div>
                <div className="form-group">
                  <label>Title <span className="required">*</span></label>
                  <input
                    type="text"
                    value={prTitle}
                    onChange={e => setPrTitle(e.target.value)}
                    disabled={prCreating}
                  />
                </div>
                <div className="form-group">
                  <label>Description</label>
                  <textarea
                    value={prBody}
                    onChange={e => setPrBody(e.target.value)}
                    rows={4}
                    disabled={prCreating}
                  />
                </div>
                {prError && <p className="pr-error">{prError}</p>}
                <div className="modal-actions">
                  <button className="btn btn-primary" onClick={handleCreatePR} disabled={prCreating}>
                    {prCreating ? 'Creating…' : 'Create Pull Request'}
                  </button>
                  <button className="btn" onClick={() => setShowPRModal(false)} disabled={prCreating}>
                    Cancel
                  </button>
                </div>
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
}

export default AgentEditor;
